name: school_admin_portal
description: "School Management Admin Portal"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  provider: ^6.1.2
  file_picker: ^8.1.3
  firebase_storage: ^12.3.4
  cached_network_image: ^3.4.1
  flutter_quill: ^10.8.5
  data_table_2: ^2.5.15
  url_launcher: ^6.3.1
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #- assets/images/
    #- assets/icons/
